# Generated by Django 3.2.5 on 2021-08-21 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_id', models.CharField(default='0', max_length=20, verbose_name='설문참가자 아이디')),
                ('situation', models.CharField(default='1', max_length=20, verbose_name='상황 번호')),
                ('gender', models.CharField(max_length=20, verbose_name='성별')),
                ('age_group', models.CharField(max_length=20, verbose_name='나이 그룹')),
                ('breathiness', models.CharField(max_length=20, verbose_name='breathiness')),
                ('smoothness', models.CharField(max_length=20, verbose_name='smoothness')),
                ('hoarseness', models.CharField(max_length=20, verbose_name='hoarseness')),
                ('variation', models.CharField(max_length=20, verbose_name='variation')),
                ('url', models.TextField(verbose_name='URL_list')),
            ],
        ),
        migrations.CreateModel(
            name='Voice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=20, verbose_name='성별')),
                ('age_group', models.CharField(max_length=20, verbose_name='나이 그룹')),
                ('preference', models.CharField(max_length=20, verbose_name='선호도')),
                ('voice_code', models.CharField(max_length=20)),
                ('audio_url', models.URLField(verbose_name='S3_URL')),
            ],
        ),
    ]
