# Generated by Django 3.2.5 on 2021-07-31 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=20, verbose_name='성별')),
                ('age_group', models.CharField(max_length=20, verbose_name='나이 그룹')),
                ('breathiness', models.CharField(max_length=20, verbose_name='breathiness')),
                ('smoothness', models.CharField(max_length=20, verbose_name='smoothness')),
                ('hoarseness', models.CharField(max_length=20, verbose_name='hoarseness')),
                ('variation', models.CharField(max_length=20, verbose_name='variation')),
                ('url', models.TextField(verbose_name='URL_list')),
            ],
        ),
    ]
