# Generated by Django 3.2.5 on 2021-08-18 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_userinput'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinput',
            name='situation',
            field=models.CharField(default='1', max_length=20, verbose_name='상황 번호'),
        ),
        migrations.AddField(
            model_name='userinput',
            name='test_id',
            field=models.CharField(default='0', max_length=20, verbose_name='설문참가자 아이디'),
        ),
    ]
